# Generated by Django 4.0.2 on 2022-02-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioWeb', '0002_collections_csvfiles_delete_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collections',
            old_name='groupName',
            new_name='colllectionName',
        ),
    ]
