# Generated by Django 4.0.2 on 2022-02-28 18:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bioWeb', '0003_rename_groupname_collections_colllectionname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collections',
            new_name='Collection',
        ),
        migrations.RenameModel(
            old_name='CSVFiles',
            new_name='CSVFile',
        ),
    ]
