# Generated by Django 4.0.2 on 2022-02-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioWeb', '0004_rename_collections_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvfile',
            old_name='groupName',
            new_name='filename',
        ),
    ]
