# Generated by Django 4.0.2 on 2022-02-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioWeb', '0005_rename_groupname_csvfile_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvfile',
            old_name='csvfile',
            new_name='csvFile',
        ),
        migrations.RenameField(
            model_name='csvfile',
            old_name='filename',
            new_name='fileName',
        ),
    ]
