# Generated by Django 4.0.2 on 2022-02-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bioWeb', '0006_rename_csvfile_csvfile_csvfile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='colllectionName',
            new_name='collectionName',
        ),
    ]
