# Generated by Django 4.0.2 on 2022-03-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioWeb', '0008_rename_groupid_csvfile_collectionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='fileName',
            field=models.CharField(max_length=30),
        ),
    ]
