# Generated by Django 4.0.2 on 2022-03-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioWeb', '0009_alter_csvfile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='csvFile',
            field=models.FileField(upload_to='csvFiles'),
        ),
    ]
